
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import type { QuestionRow } from '@/lib/supabase-types';

const SUPABASE_URL = "https://pbzptdqipvbhgefsjqlz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBienB0ZHFpcHZiaGdlZnNqcWx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzOTI0ODcsImV4cCI6MjA1Nzk2ODQ4N30.PR8BaYVOB7pdmwIU6w68fikKpP0mGIsS0hhd3IK1ZXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Type augmentation to help TypeScript recognize our tables
type CustomDatabase = Database & {
  public: {
    Tables: {
      questions: {
        Row: QuestionRow;
        Insert: Omit<QuestionRow, 'id' | 'created_at'>;
        Update: Partial<Omit<QuestionRow, 'id' | 'created_at'>>;
      };
    };
  };
};

export const supabase = createClient<CustomDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
